function g = center_top_middle(scale, config)
    g = rf.oriented.center(                 ...
            scale,                          ...
            config,                         ...
            0,                              ...
            [-config.excitation.offset 0]   ...
        );
end