function g = center_top_left(config)
    g = rf.oriented.center(                                         ...
            config,                                                 ...
            -45,                                                    ...
            [-config.excitation.offset -config.excitation.offset]   ...
        );
end