function g = surround_top_middle(config)
    g = rf.oriented.surround(               ...
            config,                         ...
            0,                              ...
            [-config.inhibition.offset 0]   ...
        );
end