function g = surround_top_left(scale, config)
    g = rf.oriented.surround(                                       ...
            scale,                                                  ...
            config,                                                 ...
            -45,                                                    ...
            [-config.inhibition.offset -config.inhibition.offset]   ...
        );
end