function g = surround_top_left(config)
    g = rf.oriented.surround(...
            config,                                                 ...
            -45,                                                     ...
            [-config.inhibition.offset -config.inhibition.offset]    ...
        );
end