function g = surround_top_middle(scale, config)
    g = rf.oriented.surround(               ...
            scale,                          ...
            config,                         ...
            0,                              ...
            [-config.inhibition.offset 0]   ...
        );
end