function g = surround(config, angle, offset)
    g = rf.utils.gaussian(              ...
            [config.size config.size],  ...
            config.inhibition.width,    ...
            config.inhibition.length,   ...
            angle, 0,                   ...
            config.inhibition.weight,	...
            offset                      ...
        );
end

