function g = surround(scale, config, angle, offset)
    g = rf.utils.gaussian(                      ...
            [config.size config.size],          ...
            (config.inhibition.width  * scale) ^ 2,   ...
            (config.inhibition.length * scale) ^ 2,   ...
            angle, 0,                           ...
            config.inhibition.weight,           ...
            offset                              ...
        );
end