function g = bottom_excitatory(config)
    g = rf.utils.gaussian(                  ...
            [config.size config.size],      ...
            config.excitation.width,        ...
            config.excitation.length,       ...
            0, 0,                           ...
            config.excitation.weight,       ...
            [config.excitation.offset 0]    ...
        );
end

