function g = center(config)
    g = fspecial('gaussian',                                ...
            [config.center.size config.center.size],        ...
            config.center.sigma                             ...
        );
end

