function g = center(scale, config)
    g = rf.utils.gaussian(                          ...
            [config.size config.size],              ...
            (config.excitation.width * scale) ^ 2,  ...
            (config.excitation.width * scale) ^ 2,  ...
            0, 0,                                   ...
            config.excitation.weight,               ...
            [0 0]                                   ...
        );
end

