function g = surround(config)
    g = fspecial('gaussian',                                ...
            [config.surround.size config.surround.size],    ...
            config.surround.sigma                           ...
        );
end

