function g = surround(scale, config)
    g = rf.utils.gaussian(                          ...
            [config.size config.size],              ...
            (config.inhibition.width * scale) ^ 2,  ...
            (config.inhibition.width * scale) ^ 2,  ...
            0, 0,                                   ...
            config.inhibition.weight,               ...
            [0 0]                                   ...
        ) * 0.95;   % Lennie & Haake
end