function g = top_inhibitory(config)
    g = rf.utils.gaussian(                  ...
            [config.size config.size],      ...
            config.inhibition.width,        ...
            config.inhibition.length,       ...
            0, 0,                           ...
            config.inhibition.weight,       ...
            [-config.inhibition.offset 0]   ...
        );
end

